platform :ios, '9.3'
use_frameworks!

target 'DYNetworking_Example' do
  pod 'DYNetworking', :path => '../'
#  pod 'ReactiveObjC'

  target 'DYNetworking_Tests' do
    inherit! :search_paths

    
  end
end
